// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: specs.proto

package specs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MachineSpec is stored in Omni in the infra provisioner state.
type MachineSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schematic     string                 `protobuf:"bytes,1,opt,name=schematic,proto3" json:"schematic,omitempty"`
	TalosVersion  string                 `protobuf:"bytes,2,opt,name=talos_version,json=talosVersion,proto3" json:"talos_version,omitempty"`
	ImageId       string                 `protobuf:"bytes,3,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`          // Glance image UUID
	InstanceId    string                 `protobuf:"bytes,4,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // Nova server UUID
	Region        string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	PublicIpv4    string                 `protobuf:"bytes,6,opt,name=public_ipv4,json=publicIpv4,proto3" json:"public_ipv4,omitempty"`
	ProjectId     string                 `protobuf:"bytes,7,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"` // OpenStack project resolved from MachineClass; recorded for Deprovision
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineSpec) Reset() {
	*x = MachineSpec{}
	mi := &file_specs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineSpec) ProtoMessage() {}

func (x *MachineSpec) ProtoReflect() protoreflect.Message {
	mi := &file_specs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineSpec.ProtoReflect.Descriptor instead.
func (*MachineSpec) Descriptor() ([]byte, []int) {
	return file_specs_proto_rawDescGZIP(), []int{0}
}

func (x *MachineSpec) GetSchematic() string {
	if x != nil {
		return x.Schematic
	}
	return ""
}

func (x *MachineSpec) GetTalosVersion() string {
	if x != nil {
		return x.TalosVersion
	}
	return ""
}

func (x *MachineSpec) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *MachineSpec) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *MachineSpec) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *MachineSpec) GetPublicIpv4() string {
	if x != nil {
		return x.PublicIpv4
	}
	return ""
}

func (x *MachineSpec) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

var File_specs_proto protoreflect.FileDescriptor

const file_specs_proto_rawDesc = "" +
	"\n" +
	"\vspecs.proto\x12\rovhcloudspecs\"\xe4\x01\n" +
	"\vMachineSpec\x12\x1c\n" +
	"\tschematic\x18\x01 \x01(\tR\tschematic\x12#\n" +
	"\rtalos_version\x18\x02 \x01(\tR\ftalosVersion\x12\x19\n" +
	"\bimage_id\x18\x03 \x01(\tR\aimageId\x12\x1f\n" +
	"\vinstance_id\x18\x04 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12\x1f\n" +
	"\vpublic_ipv4\x18\x06 \x01(\tR\n" +
	"publicIpv4\x12\x1d\n" +
	"\n" +
	"project_id\x18\a \x01(\tR\tprojectIdB<Z:github.com/ktijssen/omni-ovhcloud-infra-provider/api/specsb\x06proto3"

var (
	file_specs_proto_rawDescOnce sync.Once
	file_specs_proto_rawDescData []byte
)

func file_specs_proto_rawDescGZIP() []byte {
	file_specs_proto_rawDescOnce.Do(func() {
		file_specs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_specs_proto_rawDesc), len(file_specs_proto_rawDesc)))
	})
	return file_specs_proto_rawDescData
}

var file_specs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_specs_proto_goTypes = []any{
	(*MachineSpec)(nil), // 0: ovhcloudspecs.MachineSpec
}
var file_specs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_specs_proto_init() }
func file_specs_proto_init() {
	if File_specs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_specs_proto_rawDesc), len(file_specs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_specs_proto_goTypes,
		DependencyIndexes: file_specs_proto_depIdxs,
		MessageInfos:      file_specs_proto_msgTypes,
	}.Build()
	File_specs_proto = out.File
	file_specs_proto_goTypes = nil
	file_specs_proto_depIdxs = nil
}
